{
  "imports": [
    {
      "path": "jenkins.jinja"
    }
  ],
  "resources": [
    {
      "name": "jenkins",
      "type": "jenkins.jinja",
      "properties": {
        "zone": "us-central1-f",
        "machineType": "g1-small",
        "bootDiskType": "pd-standard",
        "bootDiskSizeGb": 10,
        "network": "default",
        "subnetwork": "default",
        "externalIP": "Ephemeral",
        "tcp80SourceRanges": "",
        "tcp443SourceRanges": "",
        "enableTcp80": true,
        "enableTcp443": true
      }
    }
  ]
}